#!/bin/sh

# Script to reset migrations for PostgreSQL
# This is needed when switching from SQLite to PostgreSQL

echo "🔄 Resetting migrations for PostgreSQL..."

# Backup existing migrations
if [ -d "prisma/migrations" ]; then
    echo "📦 Backing up existing migrations..."
    mv prisma/migrations prisma/migrations.sqlite.backup
fi

# Create new migrations directory
mkdir -p prisma/migrations

# Update migration_lock.toml for PostgreSQL
cat > prisma/migrations/migration_lock.toml << EOF
# Please do not edit this file manually
# It should be added in your version-control system (i.e. Git)
provider = "postgresql"
EOF

echo "✅ Migration lock file updated for PostgreSQL"

# Create initial migration
echo "📝 Creating initial migration for PostgreSQL..."
npx prisma migrate dev --name init_postgresql --create-only

echo "✅ Migrations reset for PostgreSQL"

